### ISSUE TITLE
Position with two monitors

### ISSUE THREAD

**Issue by Foolius** [iliags/click_storm#12]
There is a problem with setting a position for clicking with two monitors.
I have two FullHD monitors set up so that I have one plane of 3840x1080 pixels. However I can't set the x-position in the application to a value higher than 1920. Neither with 'Pick Position' nor by setting the value manually.

**Comment by iliags** [comment]
Does the number box accept a value above 1920 but not click there or does it not accept the number at all?

**Comment by Foolius** [comment]
the problem is still there
